# Site
name: 'LiOnzTec'
description: 'Tecnología en formato personal.'
logo: 'assets/images/LD70.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'blog'
email: 'lionz@gmail.com'
mailchimp-list: 'https://lionztec.github.io'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    lionz:
      name:           De Lan
      site:           https://lionztec.github.io
      avatar:         /assets/images/avatar1.jpg
      bio:            "Soñador, adicto a la tecnología y los videojuegos, humilde bloguero y aficionado amante de la fotografía."
      email:          lionz@gmail.com
      twitter:        https://twitter.com/lionz

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: lionz
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
